version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - USE_IN_MEMORY_DB=true
      - PORT=5000
    ports:
      - 5000:5000
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend
    restart: unless-stopped
